### ISSUE TITLE
cannot install drizzle on macos and windows

### ISSUE THREAD

**Issue by GiovanniCapizzi** [ConsenSys-archive/drizzle#46]
I can't add drizzle to my project because of `scrypt module` which fails to build. Already found [this](https://github.com/barrysteyn/node-scrypt/issues/192#issuecomment-493670818), and it seems to happen with NodeJs 12.  I wouldn't like to try with Node10 because scrypt doesn't seems to be manteined [anymore](https://github.com/barrysteyn/node-scrypt), is there hope for new fix soon?

```
# define NAN_DEPRECATED __attribute__((deprecated))
                                      ^
8 warnings and 7 errors generated.
make: *** [Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: make failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/Cellar/node/12.11.1/libexec/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/usr/local/Cellar/node/12.11.1/bin/node" "/usr/local/Cellar/node/12.11.1/libexec/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
[...]
gyp ERR! node -v v12.11.1
```

**Comment by jklepatch** [comment]
This does not seem to be a problem with Drizzle directly, but with the scrypt dependency of `web3`.

Not sure to understand why you don't want to try with NodeJS 10. NodeJS is the LTS (Long Term Support) version of NodeJS and for most cases it's the recommended version.

**Comment by GiovanniCapizzi** [comment]
Yes, I am sorry, I was not so clear, my request was addressed to know if this dependency would be upgraded soon, [Scrypt](https://github.com/barrysteyn/node-scrypt) has been deprecated, so if I downgrade NodeJS, it would work only for that version and I won't be able to upgrade only for one package, in the future. I asked for future maintainability of a new project. 

UPDATE:
I didn't see that was a web3 dependency, sorry.

**Comment by jklepatch** [comment]
Can you try with the latest version of Drizzle(in your package.json you can point to the latest commit of this repo).

Drizzle has updated to `web3 `1.2.1` (not released to npm yet), and it might solve your problem.

**Comment by GiovanniCapizzi** [comment]
With yarn or npm I get this error:
`error Can't add "root": invalid package version undefined.`
Is it because package.json doesn't not specify a version?

**Comment by jklepatch** [comment]
What did you put exactly in your package.json?

**Comment by GiovanniCapizzi** [comment]
I tried with "yarn add" command. Same result if I put "package":"git://...#commit" in the package.json.

If I install it with NPM it gets a webpack error. I can't put any logs here because I am without my laptop right now, sorry.

**Comment by cds-amal** [comment]
@GiovanniCapizzi can you provide a repo that demonstrates the issue? It would be helpful for us to investigate.

**Comment by GiovanniCapizzi** [comment]
Just following this [tutorial](https://www.trufflesuite.com/tutorials/getting-started-with-drizzle-and-react#install-drizzle). If you want to reproduce the issue just create a simple node (12) project (like react) and issue the yarn add command. If you want I can prepare and upload a repo for you, just let me know.

**Comment by cds-amal** [comment]
Hi @GiovanniCapizzi, 

Interesting that it fails on node v12.x.x for both Windows and OS X.
Can you specify some details about your environment to help us reproduce this issue? 
- version of node (eg v12.12.0)
- Windows Version, and environment. Are you using Windows Subsystem for Linux (WSL)?

Thanks in advance!

**Comment by msicilia** [comment]
I have same issue with MacOS Catalina 10.15.
- My version of node is v12.12.0
- Here a link to the output: 
https://gist.github.com/msicilia/6fbf58bd6410499fb3eb7e28111da479 

I know I can revert to Node 10 and it works, but it would be great to have a fix for Node 12 soon. 

Many thanks in advance.

**Comment by cds-amal** [comment]
Thank you @msicilia, this is quite helpful!

**Comment by GiovanniCapizzi** [comment]
Really sorry I forgot to answer due to work.
On MacOS with Catalina now, my Node version is v12.11.1. 
On Windows I have 12.10.0 without using WSL. 
No particularly environment used, just the windows-build-tools installed in Node to build stuffs.

**Comment by cds-amal** [comment]
Thanks @GiovanniCapizzi ! I'll work on reproducing this on OS X with your versions. Please note, that for now, we only support WSL windows build environment.

**Comment by GiovanniCapizzi** [comment]
> This does not seem to be a problem with Drizzle directly, but with the scrypt dependency of `web3`.
> 
> Not sure to understand why you don't want to try with **NodeJS 10. NodeJS is the LTS** (Long Term Support) version of NodeJS and for most cases it's the recommended version.

NodeJS just updated the LTS version, now we have 12.13.0 LTS in just few days 😆

**Comment by adrianmcli** [comment]
@GiovanniCapizzi 

I ran the following under Node `v12.13.0` on MacOS `10.14.6` (Mojave) and it worked fine:

```
yarn init -y
yarn add @drizzle/store @drizzle/react-plugin @drizzle/react-components
```

That being said, I did get a similar error on `v13.0.1`:

```
1 warning and 1 error generated.
make: *** [Release/obj.target/sha3/src/addon.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/adrianli/n/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 18.7.0
gyp ERR! command "/Users/adrianli/n/bin/node" "/Users/adrianli/n/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/adrianli/dev/temp/node_modules/sha3
```

However, this seems to be because of some libraries Web3.js is using. I've made an issue here: https://github.com/ethereum/web3.js/issues/3181

**Comment by GiovanniCapizzi** [comment]
Maybe this is caused by the same web3.js which could use [this](https://github.com/barrysteyn/node-scrypt) deprecated module. I will try again updating my node version.

>#WARNING!!! This module is deprecated. Instead, use https://nodejs.org/api/crypto.html#crypto_crypto_scrypt_password_salt_keylen_options_callback

**Comment by rattle99** [comment]
Is there a fix yet? Gives an error as of now.

**Comment by theabdulmateen** [comment]
So is there a fix, I have been struggling with the same error. can't find a fix or a workaround that works anymore.

Thanks

**Comment by Suedo** [comment]
Same problem.

Environment:
```
Ubuntu 20.04 on windows via WSL2. 
Node version : 12.19.0
```

I get the error when I use `npm install -g drizzle`

However, following [the link that OP provided](https://www.trufflesuite.com/tutorials/getting-started-with-drizzle-and-react#install-drizzle), when I use the command `npm install -g @drizzle/store` , I no longer face any issues.

Are we supposed to install `@drizzle/store` if we want to use drizzle? Asking because the page on truffle suite says `drizzle` 

![image](https://user-images.githubusercontent.com/4963779/98253024-90d46880-1fa0-11eb-995a-573ea05797d2.png)


<hr>

**Update**

It seems like `@drizzle/store`  is the way to go. The [Drizzle QuickStart](https://www.trufflesuite.com/docs/drizzle/quickstart) page says to use `npm install --save @drizzle/store`. I guess you guys should update the Truffle Suite page ?
